version: '3.9'

services:
    db:
        image: postgres:15
        container_name: db-account-service
        restart: always
        ports:
            - "${POSTGRES_PORT}:5432"
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - db_data:/var/lib/postgresql/data

volumes:
    db_data: