# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: account.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'account.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\raccount.proto\x12\naccount_v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x8a\x01\n\x07\x41\x63\x63ount\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x17\n\x0fhashed_password\x18\x03 \x01(\t\x12\x13\n\x0bis_verified\x18\x04 \x01(\x08\x12.\n\ncreated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.TimestampJ\x04\x08\x06\x10\x10\"@\n\rCreateRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x1a\n\x12\x65ncrypted_password\x18\x02 \x01(\tJ\x04\x08\x03\x10\x06\"7\n\x0e\x43reateResponse\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x11\n\tjwt_token\x18\x02 \x01(\tJ\x04\x08\x03\x10\x06\"?\n\x0cLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x1a\n\x12\x65ncrypted_password\x18\x02 \x01(\tJ\x04\x08\x03\x10\x06\"(\n\rLoginResponse\x12\x11\n\tjwt_token\x18\x01 \x01(\tJ\x04\x08\x02\x10\x06\"0\n\x14GetPublicKeyResponse\x12\x12\n\npublic_key\x18\x01 \x01(\tJ\x04\x08\x02\x10\x06\"\x1e\n\x0eGetByIdRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"9\n\x0bGetResponse\x12$\n\x07\x61\x63\x63ount\x18\x01 \x01(\x0b\x32\x13.account_v1.AccountJ\x04\x08\x02\x10\x06\"=\n\x0eGetAllResponse\x12%\n\x08\x61\x63\x63ounts\x18\x01 \x03(\x0b\x32\x13.account_v1.AccountJ\x04\x08\x02\x10\x06\x32\xd3\x02\n\x0e\x41\x63\x63ountService\x12?\n\x06Signup\x12\x19.account_v1.CreateRequest\x1a\x1a.account_v1.CreateResponse\x12<\n\x05Login\x12\x18.account_v1.LoginRequest\x1a\x19.account_v1.LoginResponse\x12H\n\x0cGetPublicKey\x12\x16.google.protobuf.Empty\x1a .account_v1.GetPublicKeyResponse\x12:\n\x03Get\x12\x1a.account_v1.GetByIdRequest\x1a\x17.account_v1.GetResponse\x12<\n\x06GetAll\x12\x16.google.protobuf.Empty\x1a\x1a.account_v1.GetAllResponseB\x1bZ\x19pkg/account_v1;account_v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'account_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\031pkg/account_v1;account_v1'
  _globals['_ACCOUNT']._serialized_start=92
  _globals['_ACCOUNT']._serialized_end=230
  _globals['_CREATEREQUEST']._serialized_start=232
  _globals['_CREATEREQUEST']._serialized_end=296
  _globals['_CREATERESPONSE']._serialized_start=298
  _globals['_CREATERESPONSE']._serialized_end=353
  _globals['_LOGINREQUEST']._serialized_start=355
  _globals['_LOGINREQUEST']._serialized_end=418
  _globals['_LOGINRESPONSE']._serialized_start=420
  _globals['_LOGINRESPONSE']._serialized_end=460
  _globals['_GETPUBLICKEYRESPONSE']._serialized_start=462
  _globals['_GETPUBLICKEYRESPONSE']._serialized_end=510
  _globals['_GETBYIDREQUEST']._serialized_start=512
  _globals['_GETBYIDREQUEST']._serialized_end=542
  _globals['_GETRESPONSE']._serialized_start=544
  _globals['_GETRESPONSE']._serialized_end=601
  _globals['_GETALLRESPONSE']._serialized_start=603
  _globals['_GETALLRESPONSE']._serialized_end=664
  _globals['_ACCOUNTSERVICE']._serialized_start=667
  _globals['_ACCOUNTSERVICE']._serialized_end=1006
# @@protoc_insertion_point(module_scope)
