name: Build

on: push

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        steps:
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Checkout
              uses: actions/checkout@v2

            - name: Checkout protobuf repository
              uses: actions/checkout@v3
              with:
                  repository: passwordhash/protobuf-files
                  path: proto

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Set up environment fil
              run: echo "${{ secrets.ENV_FILE }}" > .env

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  context: .
                  push: true
                  tags: |
                    passwordhash/account-microservice:latest
                    passwordhash/account-microservice:${{ vars.VERSION }}