name: Build

on: push

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Checkout protobuf repository
              uses: actions/checkout@v3
              with:
                  repository: passwordhash/protobuf-files
                  path: proto

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build Docker image
              run: docker build -t passwordhash/account-microservice:0.0.1 .